EVALUATE
ROW (
    "Teste",
    	CALCULATE(
    		[Total vendas] * 1.3,
    		Tb_ItensNotas[Quantidade]>20
	    )
	    +
	    CALCULATE(
    		[Total vendas] * 0.5,
    		NOT(Tb_ItensNotas[Quantidade]>20)
	    )    
)



/* Primeiro teste de velocidade
ROW (
    "Teste",
        SUMX (
            Tb_ItensNotas,
            VAR TotalVendas = [Total Vendas]
            RETURN
            IF ( [Quantidade] > 20, TotalVendas * 1.3, TotalVendas * 0.5 )
        )
)

VALUES(Tb_Vendedores)
ROW ( "Total vendas", SUMX ( Tb_ItensNotas, [Quantidade] * [Preço] ) ) */