EVALUATE
// VALUES(Tb_Vendedores)

// ROW ( "Total vendas", SUMX ( Tb_ItensNotas, [Quantidade] * [Preço] ) )

ROW("Teste", SUMX(Tb_ItensNotas, IF([Quantidade]>20, [Total vendas] * 1.3, [Total vendas] * 1.5 ) ) 